# Generated by Django 4.2.1 on 2023-06-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_tag_slug_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('draft', 'Чернетка')], default='draft', max_length=10, verbose_name='Статус'),
        ),
    ]
